// generated from gentext.pl Messages.xlsx
#ifndef __STRING_TABLE_RESOURCE_H__
#define __STRING_TABLE_RESOURCE_H__
#define IDS_MDK_UNTERMINATED_COMMENT                 10000
#define IDS_MDK_UNTERMINATED_STRING_REGEX_OCTET      10001
#define IDS_MDK_INSUFFICIENT_MEMORY                  10002
#define IDS_MDK_NUMBER_PARSE_ERRROR                  10003
#define IDS_MDK_INVALID_CHAR                         10004
#define IDS_MDK_SELECTOR_PARSE_ERROR                 10005
#define IDS_MDK_INTERNAL_ERROR                       10006
#define IDS_MDK_ALREADY_REGISTERED                   10007
#define IDS_MDK_CANNOT_REGISTER_WORD                 10008
#define IDS_MDK_PARAMETER_DUPLICATE                  10009
#define IDS_MDK_ATTRIBUTE_DUPLICATE                  10010
#define IDS_MDK_INVALID_FILE_ATTRIBUTE_DOT           10011
#define IDS_MDK_INVALID_FILE_ATTRIBUTE_DOUBLE_COLON  10012
#define IDS_MDK_INVALID_REFERENCE_DOT                10013
#define IDS_MDK_INVALID_REFERENCE_DOUBLE_COLON       10014
#define IDS_MDK_INVALID_PLUS_NUMBER                  10015
#define IDS_MDK_INVALID_MINUS_NUMBER                 10016
#define IDS_MDK_NOT_NUMBER_AFTER_LTIN_TAG            10017
#define IDS_MDK_NOT_CLOSED_LTIN_TAG                  10018
#define IDS_MDK_NOT_NUMBER_AFTER_LBRACE_IN_TAG       10019
#define IDS_MDK_NOT_CLOSED_LBRACE_IN_TAG             10020
#define IDS_MDK_NOT_NUMBER_AFTER_LPARENTHESIS_IN_TAG 10021
#define IDS_MDK_NOT_CLOSED_LPARENTHESIS_IN_TAG       10022
#define IDS_MDK_PARAMETER_PARSE_ERROR_IN_TAG         10023
#define IDS_MDK_INVALID_CHAR_DECORATION              10024
#define IDS_MDK_INVALID_SYMBOL_IN_TAG                10025
#define IDS_MDK_INVALID_CHARACTOR_IN_NAME            10026
#define IDS_MDK_INVALID_CHARACTOR_IN_LABEL           10027
#define IDS_MDK_INVALID_SELECTOR_SYNTAX              10028
#define IDS_MDK_INVALID_NEXT_CONDITION               10029
#define IDS_MDK_INVALID_TEXT_IN_NEXT_COMMAND         10030
#define IDS_MDK_INVALID_RUBY_SYNTAX                  10031
#define IDS_MDK_INVALID_REGISTER_RUBY_SYNTAX         10032
#define IDS_MDK_INVALID_CHARACTOR_DECORATION_SYNTAX  10033
#define IDS_MDK_INVALID_INLINE_GRAPHICS_SYNTAX       10034
#define IDS_MDK_INVALID_EMOJI_SYNTAX                 10035
#define IDS_MDK_UNKNOWN_SYNTAX                       10036
#define IDS_MDK_UNTARMINATED_TAG                     10037
#endif
